# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required

r_binary_install:
 - raster
 - rgdal
 - geosphere
 - RCurl
 - plyr
 - reshape2
 - ggplot2
 - sp
 - stringr
 - rgeos
 - spatial.tools # there is an error with the repo version
 - snow

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: true
