language: r
sudo: required

before_install:
 - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable

r_binary_install:
 - raster
 - rgdal
 - rgdal
 - geosphere
 - RCurl
 - plyr
 - reshape2
 - ggplot2
 - sp
 - stringr
 - rgeos
 - spatial.tools # there is an error with the repo version
 - snow

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: true
