# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
    # gfcanalysis R imports deps
  - ./travis-tool.sh install_r_binary raster rgdal geosphere RCurl plyr reshape2 ggplot2 sp stringr
  - ./travis-tool.sh install_r rgeos spatial.tools # there is an error with the repo version
    # gfcanalysis R suggested
  - ./travis-tool.sh install_r_binary testthat foreach itertools doSNOW

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
